version: 0.2
env:
    secrets-manager:
        API_KEY_STAGING: "FunApiServer/ApiGateway:staging"
phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - npm install
    pre_build:
        commands:
            - npx ts-node tests/contractLoader.ts
            - aws secretsmanager get-secret-value --secret-id PrivateKeys --region us-west-2 --query SecretString --output text > secrets.json
            - export $(jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" secrets.json)
            # Use the environment variables in your build process
            - echo $TEST_PRIVATE_KEY
            - echo $FUNDER_PRIVATE_KEY
            - echo $WALLET_PRIVATE_KEY
            - echo $GOERLI_FUNDER_PRIVATE_KEY
            - echo $WALLET_PRIVATE_KEY_2
    build:
        commands:
            - npm run test-goerli
artifacts:
    files:
        - "**/*"
